@TaskManagementSystem_HostAddress = http://localhost:5094
@ApiKey=SARMIENTOKEY
@AdminToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFkbWluIiwicm9sZSI6IkFkbWluIiwibmJmIjoxNzc2MzQ2OTU2LCJleHAiOjE3NzYzNTA1NTYsImlhdCI6MTc3NjM0Njk1Nn0.hVYZ4P0LlgKitd4TfLzIFz1omCP6cDRT0NL_CU_LOdU
@ManagerToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1hbmFnZXIiLCJyb2xlIjoiTWFuYWdlciIsIm5iZiI6MTc3NjM0ODE4NCwiZXhwIjoxNzc2MzUxNzg0LCJpYXQiOjE3NzYzNDgxODR9.TPsex_lpDC0TAKSrp2wH4LQL4UA3Cp87ijulz7omB8g
@EmployeeToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImVtcGxveWVlIiwicm9sZSI6IkVtcGxveWVlIiwibmJmIjoxNzc2MzQ4MTI5LCJleHAiOjE3NzYzNTE3MjksImlhdCI6MTc3NjM0ODEyOX0.An9WlK06tZgteyMgqLfeHu2p9QQFfKKLHsdPizQ2eXc

### 1. Test API Key Protection (Should fail without header)
POST {{TaskManagementSystem_HostAddress}}/api/auth/Login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### 2. Login as Admin (Requires API Key)
# This should return a JWT. Copy it and paste it into the @AdminToken variable above.
POST {{TaskManagementSystem_HostAddress}}/api/auth/Login
X-API-KEY: {{ApiKey}}
Content-Type: application/json

{
  "username": "manager",
  "password": "manager"
}

### 3. Get Tasks
GET {{TaskManagementSystem_HostAddress}}/api/tasks
Accept: application/json
X-API-KEY: {{ApiKey}}
Authorization: Bearer {{AdminToken}}


### 4. Create Task (Manager/Admin only)
POST {{TaskManagementSystem_HostAddress}}/api/tasks
X-API-KEY: {{ApiKey}}
Authorization: Bearer {{AdminToken}}
Content-Type: application/json

{
  "title": "New Task",
  "description": "Finish the API"
}

### 5. Admin - Get Users (Admin Only)
GET {{TaskManagementSystem_HostAddress}}/api/admin/Users
X-API-KEY: {{ApiKey}}
Authorization: Bearer {{AdminToken}}

### 6. Test Rate Limiting (Admin endpoint - 3 req/min)
# Click "Send Request" 4 times quickly. 
# The 4th should return 429 Too Many Requests.
GET {{TaskManagementSystem_HostAddress}}/api/admin/users
X-API-KEY: {{ApiKey}}
Authorization: Bearer {{AdminToken}}

### 7. Test Role Restriction (Unauthorized Access)
# Log in as an Employee first, get that token, and try to DELETE a user.
# Should return 403 Forbidden.
DELETE {{TaskManagementSystem_HostAddress}}/api/admin/users/1
X-API-KEY: {{ApiKey}}
Authorization: Bearer {{EmployeeToken}}

###