@TaskManagementSystem_HostAddress = http://localhost:5094
@ApiKey=SARMIENTOKEY
@AdminToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFkbWluIiwicm9sZSI6IkFkbWluIiwibmJmIjoxNzc2MzQ0ODc3LCJleHAiOjE3NzYzNDg0NzcsImlhdCI6MTc3NjM0NDg3N30.f_ka_IaAAuBLf9Cr2dPWrVcf1f9KoP1IY5DEEYszLc8
@EmployeeToken=paste_employee_token_here

### 1. Test API Key Protection (Should fail without header)
POST {{TaskManagementSystem_HostAddress}}/api/auth/Login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### 2. Login as Admin (Requires API Key)
# This should return a JWT. Copy it and paste it into the @AdminToken variable above.
POST {{TaskManagementSystem_HostAddress}}/api/auth/Login
X-API-KEY: {{ApiKey}}
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### 3. Get Tasks
GET {{TaskManagementSystem_HostAddress}}/api/tasks
Accept: application/json
X-API-KEY: {{ApiKey}}
Authorization: Bearer {{AdminToken}}


### 4. Create Task (Manager/Admin only)
POST {{TaskManagementSystem_HostAddress}}/api/tasks
X-API-KEY: {{ApiKey}}
Authorization: Bearer {{AdminToken}}
Content-Type: application/json

{
  "title": "New Task",
  "description": "Finish the API"
}

### 5. Admin - Get Users (Admin Only)
GET {{TaskManagementSystem_HostAddress}}/api/admin/users
X-API-KEY: {{ApiKey}}
Authorization: Bearer {{AdminToken}}

### 6. Test Rate Limiting (Admin endpoint - 3 req/min)
# Click "Send Request" 4 times quickly. 
# The 4th should return 429 Too Many Requests.
GET {{TaskManagementSystem_HostAddress}}/api/admin/users
X-API-KEY: {{ApiKey}}
Authorization: Bearer {{AdminToken}}

### 7. Test Role Restriction (Unauthorized Access)
# Log in as an Employee first, get that token, and try to DELETE a user.
# Should return 403 Forbidden.
DELETE {{TaskManagementSystem_HostAddress}}/api/admin/users/1
X-API-KEY: {{ApiKey}}
Authorization: Bearer {{EmployeeToken}}