@TaskManagementSystem_HostAddress = http://localhost:5094
@ApiKey = SARMIENTOKEY

@AdminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFkbWluIiwicm9sZSI6IkFkbWluIiwibmJmIjoxNzc2MzUyODQxLCJleHAiOjE3NzYzNTY0NDEsImlhdCI6MTc3NjM1Mjg0MX0.dF1mjOBtVX6-l5B1OK_T_7y0fVtI3880GdNa9Y5HixM
@ManagerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1hbmFnZXIiLCJyb2xlIjoiTWFuYWdlciIsIm5iZiI6MTc3NjM1Mjg1MiwiZXhwIjoxNzc2MzU2NDUyLCJpYXQiOjE3NzYzNTI4NTJ9.s0XC06P62XlpSXD576l0YmjsHflVMB2VjxtYZfbYe5U
@EmployeeToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImVtcGxveWVlIiwicm9sZSI6IkVtcGxveWVlIiwibmJmIjoxNzc2MzUyODY2LCJleHAiOjE3NzYzNTY0NjYsImlhdCI6MTc3NjM1Mjg2Nn0.jx-Ay8wFUmCxAlJz-ARHfwBHtFI9vauwVK2O_Evqx5A

### test missing API key (401)
POST {{TaskManagementSystem_HostAddress}}/api/auth/Login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### login (Admin) - Test Rate Limit (5 req/min) (429)
POST {{TaskManagementSystem_HostAddress}}/api/auth/Login
X-API-KEY: {{ApiKey}}
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### login (Manager) - Test Rate Limit (5 req/min) (429)
POST {{TaskManagementSystem_HostAddress}}/api/auth/Login
X-API-KEY: {{ApiKey}}
Content-Type: application/json

{
  "username": "manager",
  "password": "manager"
}

### login (Employee) - Test Rate Limit (5 req/min) (429)
POST {{TaskManagementSystem_HostAddress}}/api/auth/Login
X-API-KEY: {{ApiKey}}
Content-Type: application/json

{
  "username": "employee",
  "password": "employee"
}

### admin: get all users (3 req/min limit) (429)
GET {{TaskManagementSystem_HostAddress}}/api/admin/users
X-API-KEY: {{ApiKey}}
Authorization: Bearer {{AdminToken}}

### admin: get all users (3 req/min limit) (429)
DELETE {{TaskManagementSystem_HostAddress}}/api/admin/users/1
X-API-KEY: {{ApiKey}}
Authorization: Bearer {{AdminToken}}

### employee accessing admin funcs (403)
GET {{TaskManagementSystem_HostAddress}}/api/admin/users
X-API-KEY: {{ApiKey}}
Authorization: Bearer {{EmployeeToken}}

### manager: create task (10 req/min limit) (429)
POST {{TaskManagementSystem_HostAddress}}/api/tasks
X-API-KEY: {{ApiKey}}
Authorization: Bearer {{ManagerToken}}
Content-Type: application/json

{
  "title": "Managerial Task",
  "description": "Assigned by Manager"
}

### employee: get tasks (20 req/min limit) (429)
GET {{TaskManagementSystem_HostAddress}}/api/tasks
X-API-KEY: {{ApiKey}}
Authorization: Bearer {{EmployeeToken}}

### employee accessing manager funcs (403)
POST {{TaskManagementSystem_HostAddress}}/api/tasks
X-API-KEY: {{ApiKey}}
Authorization: Bearer {{EmployeeToken}}
Content-Type: application/json

{
  "title": "sample task",
  "description": "hnd i2 pwd"
}

### admin rate limit (3 req/min) (429)
GET {{TaskManagementSystem_HostAddress}}/api/admin/users
X-API-KEY: {{ApiKey}}
Authorization: Bearer {{AdminToken}}

### global task get limit (20 req/min) (429)
GET {{TaskManagementSystem_HostAddress}}/api/tasks
X-API-KEY: {{ApiKey}}
Authorization: Bearer {{AdminToken}}

###
GET {{TaskManagementSystem_HostAddress}}/api/tasks
X-API-KEY: {{ApiKey}}
Authorization: Bearer {{ManagerToken}}

###
GET {{TaskManagementSystem_HostAddress}}/api/tasks
X-API-KEY: {{ApiKey}}
Authorization: Bearer {{EmployeeToken}}